{% set name = "tweetynet" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tweetynet-{{ version }}.tar.gz
  sha256: 75ff2c12d63f19aa8191bf9b0a304ea628f4f6f0b13631a620f393d67a6e613c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core
  run:
    - python >=3.7
    - pytorch >=1.7.1
    - vak >=0.4.0

test:
  imports:
    - tweetynet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tweetynet/
  summary: neural network that segments and labels birdsong and other animal vocalizations
  dev_url: https://github.com/yardencsGitHub/tweetynet
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
